<a href="https://colab.research.google.com/github/Xfinity-bot/ML-Notebooks/blob/main/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)

# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


None
Epoch 1/200
24/24 - 3s - loss: 1.2448 - accuracy: 0.3083 - 3s/epoch - 105ms/step
Epoch 2/200
24/24 - 0s - loss: 1.0997 - accuracy: 0.3083 - 89ms/epoch - 4ms/step
Epoch 3/200
24/24 - 0s - loss: 0.9755 - accuracy: 0.5833 - 94ms/epoch - 4ms/step
Epoch 4/200
24/24 - 0s - loss: 0.9116 - accuracy: 0.6833 - 70ms/epoch - 3ms/step
Epoch 5/200
24/24 - 0s - loss: 0.8599 - accuracy: 0.8750 - 67ms/epoch - 3ms/step
Epoch 6/200
24/24 - 0s - loss: 0.8108 - accuracy: 0.8833 - 81ms/epoch - 3ms/step
Epoch 7/200
24/24 - 0s - loss: 0.7593 - accuracy: 0.8000 - 133ms/epoch - 6ms/step
Epoch 8/200
24/24 - 0s - loss: 0.7087 - accuracy: 0.7333 - 57ms/epoch - 2ms/step
Epoch 9/200
24/24 - 0s - loss: 0.6631 - accuracy: 0.6917 - 67ms/epoch - 3ms/step
Epoch 10/200
24/24 - 0s - loss: 0.6187 - accuracy: 0.7000 - 64ms/epoch - 3ms/step
Epoch 11/200
24/24 - 0s - loss: 0.5814 - accuracy: 0.7167 - 103ms/epoch - 4ms/step
Epoch 12/200
24/24 - 0s - loss: 0.5479 - accuracy: 0.7583 - 142ms/epoch - 6ms/step
Epoch 13/200
24/2